#Permissões para usar os comandos
#Bypass - 4tplugins.comando.*

#Fly - 4tplugins.fly
#Skulls - 4tplugins.head
#Gamemode - 4tplugins.comando.gm | Ou em vez de gm pode colocar gamemode
#Clear -  4tplugins.comando.clear